"""initial schema

Revision ID: dde641b78bb9
Revises:
Create Date: 2026-02-07 21:47:32.921846

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dde641b78bb9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="auditaction", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_audit_logs_timestamp", "audit_logs", ["timestamp"], unique=False)
    op.create_index(
        "ix_audit_logs_user_timestamp", "audit_logs", ["user_id", "timestamp"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("ico", sa.String(length=8), nullable=False),
        sa.Column("dic", sa.String(length=20), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("pohoda_id", sa.Integer(), nullable=True),
        sa.Column("pohoda_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index("ix_customers_company_name", "customers", ["company_name"], unique=False)
    op.create_index(op.f("ix_customers_customers_ico"), "customers", ["ico"], unique=True)
    op.create_index("ix_customers_email", "customers", ["email"], unique=False)
    op.create_table(
        "documents",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "VYKRES",
                "ATESTACE",
                "WPS",
                "PRUVODKA",
                "FAKTURA",
                "NABIDKA",
                "OBJEDNAVKA",
                "PROTOKOL",
                "OSTATNI",
                name="documentcategory",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index("ix_documents_category", "documents", ["category"], unique=False)
    op.create_index("ix_documents_entity", "documents", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "pohoda_sync_logs",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("EXPORT", "IMPORT", name="syncdirection", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("pohoda_doc_number", sa.String(length=50), nullable=True),
        sa.Column("xml_request", sa.Text(), nullable=True),
        sa.Column("xml_response", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "ERROR", name="syncstatus", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pohoda_sync_logs")),
    )
    op.create_index(
        "ix_pohoda_sync_logs_entity", "pohoda_sync_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_pohoda_sync_logs_status", "pohoda_sync_logs", ["status"], unique=False)
    op.create_index(
        "ix_pohoda_sync_logs_synced_at", "pohoda_sync_logs", ["synced_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "OBCHODNIK",
                "TECHNOLOG",
                "VEDENI",
                "UCETNI",
                name="userrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index("ix_users_active", "users", ["is_active"], unique=False)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "orders",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "POPTAVKA",
                "NABIDKA",
                "OBJEDNAVKA",
                "VYROBA",
                "EXPEDICE",
                "FAKTURACE",
                "DOKONCENO",
                name="orderstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "NORMAL",
                "HIGH",
                "URGENT",
                name="orderpriority",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("pohoda_id", sa.Integer(), nullable=True),
        sa.Column("pohoda_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index("ix_orders_due_date", "orders", ["due_date"], unique=False)
    op.create_index(op.f("ix_orders_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_orders_number"), "orders", ["number"], unique=True)
    op.create_index(op.f("ix_orders_orders_status"), "orders", ["status"], unique=False)
    op.create_index("ix_orders_status_priority", "orders", ["status", "priority"], unique=False)
    op.create_table(
        "calculations",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "APPROVED",
                "OFFERED",
                name="calculationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("material_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("labor_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cooperation_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("overhead_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("margin_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("margin_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_calculations_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculations")),
    )
    op.create_index(
        op.f("ix_calculations_calculations_order_id"), "calculations", ["order_id"], unique=False
    )
    op.create_index("ix_calculations_status", "calculations", ["status"], unique=False)
    op.create_table(
        "inbox_messages",
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("from_email", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "POPTAVKA",
                "OBJEDNAVKA",
                "REKLAMACE",
                "DOTAZ",
                "PRILOHA",
                name="inboxclassification",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PROCESSING",
                "PROCESSED",
                "ESCALATED",
                name="inboxstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_inbox_messages_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_inbox_messages_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_messages")),
    )
    op.create_index(
        "ix_inbox_messages_classification", "inbox_messages", ["classification"], unique=False
    )
    op.create_index(
        op.f("ix_inbox_messages_inbox_messages_customer_id"),
        "inbox_messages",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbox_messages_inbox_messages_from_email"),
        "inbox_messages",
        ["from_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbox_messages_inbox_messages_message_id"),
        "inbox_messages",
        ["message_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_inbox_messages_inbox_messages_order_id"),
        "inbox_messages",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbox_messages_inbox_messages_status"), "inbox_messages", ["status"], unique=False
    )
    op.create_index(
        "ix_inbox_messages_status_received",
        "inbox_messages",
        ["status", "received_at"],
        unique=False,
    )
    op.create_table(
        "offers",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SENT",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                name="offerstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("pohoda_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_offers_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
    )
    op.create_index(op.f("ix_offers_offers_number"), "offers", ["number"], unique=True)
    op.create_index(op.f("ix_offers_offers_order_id"), "offers", ["order_id"], unique=False)
    op.create_index("ix_offers_status", "offers", ["status"], unique=False)
    op.create_index("ix_offers_valid_until", "offers", ["valid_until"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("material", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("dn", sa.String(length=20), nullable=True),
        sa.Column("pn", sa.String(length=20), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("drawing_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(
        op.f("ix_order_items_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_table(
        "calculation_items",
        sa.Column("calculation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "cost_type",
            sa.Enum(
                "MATERIAL",
                "LABOR",
                "COOPERATION",
                "OVERHEAD",
                name="costtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calculations.id"],
            name=op.f("fk_calculation_items_calculation_id_calculations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_items")),
    )
    op.create_index(
        op.f("ix_calculation_items_calculation_items_calculation_id"),
        "calculation_items",
        ["calculation_id"],
        unique=False,
    )
    op.create_index(
        "ix_calculation_items_cost_type", "calculation_items", ["cost_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_calculation_items_cost_type", table_name="calculation_items")
    op.drop_index(
        op.f("ix_calculation_items_calculation_items_calculation_id"),
        table_name="calculation_items",
    )
    op.drop_table("calculation_items")
    op.drop_index(op.f("ix_order_items_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_offers_valid_until", table_name="offers")
    op.drop_index("ix_offers_status", table_name="offers")
    op.drop_index(op.f("ix_offers_offers_order_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_offers_number"), table_name="offers")
    op.drop_table("offers")
    op.drop_index("ix_inbox_messages_status_received", table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_inbox_messages_status"), table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_inbox_messages_order_id"), table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_inbox_messages_message_id"), table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_inbox_messages_from_email"), table_name="inbox_messages")
    op.drop_index(op.f("ix_inbox_messages_inbox_messages_customer_id"), table_name="inbox_messages")
    op.drop_index("ix_inbox_messages_classification", table_name="inbox_messages")
    op.drop_table("inbox_messages")
    op.drop_index("ix_calculations_status", table_name="calculations")
    op.drop_index(op.f("ix_calculations_calculations_order_id"), table_name="calculations")
    op.drop_table("calculations")
    op.drop_index("ix_orders_status_priority", table_name="orders")
    op.drop_index(op.f("ix_orders_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_orders_number"), table_name="orders")
    op.drop_index(op.f("ix_orders_orders_customer_id"), table_name="orders")
    op.drop_index("ix_orders_due_date", table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_users_users_email"), table_name="users")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index("ix_users_active", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_pohoda_sync_logs_synced_at", table_name="pohoda_sync_logs")
    op.drop_index("ix_pohoda_sync_logs_status", table_name="pohoda_sync_logs")
    op.drop_index("ix_pohoda_sync_logs_entity", table_name="pohoda_sync_logs")
    op.drop_table("pohoda_sync_logs")
    op.drop_index("ix_documents_entity", table_name="documents")
    op.drop_index("ix_documents_category", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_customers_email", table_name="customers")
    op.drop_index(op.f("ix_customers_customers_ico"), table_name="customers")
    op.drop_index("ix_customers_company_name", table_name="customers")
    op.drop_table("customers")
    op.drop_index("ix_audit_logs_user_timestamp", table_name="audit_logs")
    op.drop_index("ix_audit_logs_timestamp", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
