"""add user_points table

Revision ID: e6c0d56e02fa
Revises: dde641b78bb9
Create Date: 2026-02-08 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6c0d56e02fa"
down_revision: str | None = "dde641b78bb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_points",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "order_status_change",
                "calculation_complete",
                "document_upload",
                "order_complete",
                name="pointsaction",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_points_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_points")),
    )
    op.create_index(
        op.f("ix_user_points_user_points_user_id"),
        "user_points",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_points_user_points_user_id"), table_name="user_points")
    op.drop_table("user_points")
    op.execute("DROP TYPE IF EXISTS pointsaction")
    # ### end Alembic commands ###
